Supporting Context Provider
gamiphy/loyalty-station-react-native-sdk pull request #2
Opened 2020-09-03 13:20 UTC by abdallah-gamiphy

2020-09-03 13:36 UTC, riyad-gamiphy commented on package.json
> +    "lib"
Please add readme file

2020-09-03 13:36 UTC, riyad-gamiphy commented on src/components/LoyaltyStationWebview.tsx
> +    initScript?: string
Is this used?

2020-09-03 13:36 UTC, riyad-gamiphy commented on src/components/LoyaltyStationWebview.tsx
> +    isAuthPage?: () => boolean,
Is this used?

2020-09-03 13:36 UTC, riyad-gamiphy commented on README.md
> +# Gmiphy Loyalty Station SDK
Please change to
Gamiphy Loyalty Station
React Native SDK

2020-09-03 13:36 UTC, riyad-gamiphy commented on README.md
> +Gamiphy Loyalty Station is available through [npm](https://www.npmjs.com/package/@gamiphy/loyality-station-react-native-sdk), To install:
Please change to `To install:`

2020-09-03 13:36 UTC, riyad-gamiphy commented on README.md
> +Gamiphy Loyalty Station is available through [npm](https://www.npmjs.com/package/@gamiphy/loyality-station-react-native-sdk), To install:
Please add peer dependencies requirement

2020-09-03 13:36 UTC, riyad-gamiphy commented on README.md
> +import {LoyaltyStation} from "@gamiphy/loyality-station-react-native-sdk"
typo on loyality

2020-09-03 13:36 UTC, riyad-gamiphy commented on README.md
> +You can usee the use the [hooks](https://reactjs.org/docs/hooks-intro.html) based API to access the Loyalty Station functionality :
typo on usee

2020-09-03 13:36 UTC, riyad-gamiphy commented on README.md
> +You can usee the use the [hooks](https://reactjs.org/docs/hooks-intro.html) based API to access the Loyalty Station functionality :
no need to add a link for hooks. Just provide your functionality

2020-09-03 13:36 UTC, riyad-gamiphy commented on package.json
> +    "react": "16.13.1",
Peer dependencies shouldn't be strict with the patch version level.
It would be better to change to something like this ^16.x

2020-09-03 13:40 UTC, riyad-gamiphy requested changes

2020-09-03 13:40 UTC, riyad-gamiphy commented on README.md
> +<LoyaltyStation config={config:WebviewConfig}>
Please change WebviewConfig to Config

2020-09-03 13:40 UTC, riyad-gamiphy commented on README.md
> +You can usee the use the [hooks](https://reactjs.org/docs/hooks-intro.html) based API to access the Loyalty Station functionality :
Please describe the functionalities provided by useLoyaltyStation in a table

2020-09-04 09:10 UTC, abdallah-gamiphy commented
@riyad-gamiphy README.md is updated

2020-09-05 07:18 UTC, riyad-gamiphy commented
@abdallah-gamiphy Can you please add code documentation?

2020-09-05 16:23 UTC, abdallah-gamiphy commented
@riyad-gamiphy Code documentation done.

2020-09-06 07:09 UTC, riyad-gamiphy approved these changes

2020-09-06 07:09 UTC, merged